-- =====================================================================
-- SEED — vazio de proposito.
-- Os posts de teste foram removidos em 29/07/2026 (zeragem do blog).
-- O blog comeca limpo: crie posts reais pelo fluxo oficial.
-- =====================================================================
